name: Simulated CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: 🧱 Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Checkout Code
        run: echo "Checking out code..."
      - name: Setup Node.js
        run: echo "Setting up Node.js..."

  lint:
    name: 🧹 Lint Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Run ESLint
        run: echo "Linting code..."

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Run Tests on Node.js ${{ matrix.node-version }}
        run: echo "Running tests on Node.js ${{ matrix.node-version }}..."

  build:
    name: 🛠 Build Project
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Build Frontend
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Building frontend... (delay: $DELAY sec)"
          sleep $DELAY

      - name: Build Backend
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Building backend... (delay: $DELAY sec)"
          sleep $DELAY

  deploy:
    name: 🚀 Deploy Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Simulate Deployment
        run: echo "Simulating deployment to production..."

  health-check:
    name: ✅ Health Check
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Simulate Delay
        run: |
          DELAY=$((RANDOM % 5 + 1))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Run Health Check
        run: echo "Running health check..."
